/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as MinhasBuscasRouteImport } from './routes/minhas-buscas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as CalculadoraMudancaRouteImport } from './routes/calculadora-mudanca'
import { Route as CalculadoraItbiRouteImport } from './routes/calculadora-itbi'
import { Route as CalculadoraFinanciamentoRouteImport } from './routes/calculadora-financiamento'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContaIndexRouteImport } from './routes/conta.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VisitaCheckinTokenRouteImport } from './routes/visita-checkin.$token'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as QueroAnunciarTenantSlugRouteImport } from './routes/quero-anunciar.$tenantSlug'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as ImovelSlugRouteImport } from './routes/imovel.$slug'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as CorretorSlugRouteImport } from './routes/corretor.$slug'
import { Route as ContaVisitasRouteImport } from './routes/conta.visitas'
import { Route as ContaPerfilRouteImport } from './routes/conta.perfil'
import { Route as ContaFavoritosRouteImport } from './routes/conta.favoritos'
import { Route as ContaBuscasRouteImport } from './routes/conta.buscas'
import { Route as AvaliacaoTenantSlugRouteImport } from './routes/avaliacao.$tenantSlug'
import { Route as AppVisitasRouteImport } from './routes/app.visitas'
import { Route as AppTarefasRouteImport } from './routes/app.tarefas'
import { Route as AppSiteRouteImport } from './routes/app.site'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppPortaisRouteImport } from './routes/app.portais'
import { Route as AppEncurtadorRouteImport } from './routes/app.encurtador'
import { Route as AppContratacaoRouteImport } from './routes/app.contratacao'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCartoriosRouteImport } from './routes/app.cartorios'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminPlanosRouteImport } from './routes/admin.planos'
import { Route as AdminModulosRouteImport } from './routes/admin.modulos'
import { Route as AdminLimitesRouteImport } from './routes/admin.limites'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminFlagsRouteImport } from './routes/admin.flags'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as ContaChatIndexRouteImport } from './routes/conta.chat.index'
import { Route as AppSiteIndexRouteImport } from './routes/app.site.index'
import { Route as AppLocacaoIndexRouteImport } from './routes/app.locacao.index'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppImoveisIndexRouteImport } from './routes/app.imoveis.index'
import { Route as AppFinanceiroIndexRouteImport } from './routes/app.financeiro.index'
import { Route as AppEmpreendimentosIndexRouteImport } from './routes/app.empreendimentos.index'
import { Route as AppCorretoresIndexRouteImport } from './routes/app.corretores.index'
import { Route as AppContratosIndexRouteImport } from './routes/app.contratos.index'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppComissoesIndexRouteImport } from './routes/app.comissoes.index'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as ContaChatIdRouteImport } from './routes/conta.chat.$id'
import { Route as AppSiteWidgetsRouteImport } from './routes/app.site.widgets'
import { Route as AppSiteBlogRouteImport } from './routes/app.site.blog'
import { Route as AppLeadsConfiguracaoRouteImport } from './routes/app.leads.configuracao'
import { Route as AppLeadsIdRouteImport } from './routes/app.leads.$id'
import { Route as AppImoveisNovoRouteImport } from './routes/app.imoveis.novo'
import { Route as AppImoveisCompararRouteImport } from './routes/app.imoveis.comparar'
import { Route as AppImoveisIdRouteImport } from './routes/app.imoveis.$id'
import { Route as AppFinanceiroNovoRouteImport } from './routes/app.financeiro.novo'
import { Route as AppFinanceiroIdRouteImport } from './routes/app.financeiro.$id'
import { Route as AppEmpreendimentosIdRouteImport } from './routes/app.empreendimentos.$id'
import { Route as AppCorretoresNovoRouteImport } from './routes/app.corretores.novo'
import { Route as AppCorretoresIdRouteImport } from './routes/app.corretores.$id'
import { Route as AppContratosNovoRouteImport } from './routes/app.contratos.novo'
import { Route as AppContratosModelosRouteImport } from './routes/app.contratos.modelos'
import { Route as AppContratosIdRouteImport } from './routes/app.contratos.$id'
import { Route as AppConfiguracoesWebhooksRouteImport } from './routes/app.configuracoes.webhooks'
import { Route as AppConfiguracoesSegurancaRouteImport } from './routes/app.configuracoes.seguranca'
import { Route as AppConfiguracoesScoringRouteImport } from './routes/app.configuracoes.scoring'
import { Route as AppConfiguracoesPrivacidadeRouteImport } from './routes/app.configuracoes.privacidade'
import { Route as AppConfiguracoesPlanoContasRouteImport } from './routes/app.configuracoes.plano-contas'
import { Route as AppConfiguracoesNotificacoesRouteImport } from './routes/app.configuracoes.notificacoes'
import { Route as AppConfiguracoesModulosRouteImport } from './routes/app.configuracoes.modulos'
import { Route as AppConfiguracoesImportarRouteImport } from './routes/app.configuracoes.importar'
import { Route as AppConfiguracoesImobiliariaRouteImport } from './routes/app.configuracoes.imobiliaria'
import { Route as AppConfiguracoesGoliveRouteImport } from './routes/app.configuracoes.golive'
import { Route as AppConfiguracoesFunisRouteImport } from './routes/app.configuracoes.funis'
import { Route as AppConfiguracoesEquipeRouteImport } from './routes/app.configuracoes.equipe'
import { Route as AppConfiguracoesDominiosRouteImport } from './routes/app.configuracoes.dominios'
import { Route as AppConfiguracoesChecklistRouteImport } from './routes/app.configuracoes.checklist'
import { Route as AppConfiguracoesCentrosCustoRouteImport } from './routes/app.configuracoes.centros-custo'
import { Route as AppConfiguracoesCamposRouteImport } from './routes/app.configuracoes.campos'
import { Route as AppConfiguracoesCadenciasRouteImport } from './routes/app.configuracoes.cadencias'
import { Route as AppConfiguracoesBrandingRouteImport } from './routes/app.configuracoes.branding'
import { Route as AppConfiguracoesApiRouteImport } from './routes/app.configuracoes.api'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as ApiPublicHealthRouteImport } from './routes/api.public.health'
import { Route as SiteSlugPPageSlugRouteImport } from './routes/site.$slug.p.$pageSlug'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as AppContratosIdImprimirRouteImport } from './routes/app.contratos.$id.imprimir'
import { Route as ApiPublicWebhooksDeliverRouteImport } from './routes/api.public.webhooks.deliver'
import { Route as ApiPublicV1LeadsRouteImport } from './routes/api.public.v1.leads'
import { Route as ApiPublicV1ImoveisRouteImport } from './routes/api.public.v1.imoveis'
import { Route as ApiPublicCronVisitasNotificacoesRouteImport } from './routes/api.public.cron.visitas-notificacoes'
import { Route as ApiPublicCronSnapshotRouteImport } from './routes/api/public/cron.snapshot'
import { Route as ApiPublicCronBuscasAlertasRouteImport } from './routes/api.public.cron.buscas-alertas'
import { Route as ApiPublicSitemapTenantSlugSitemapDotxmlRouteImport } from './routes/api.public.sitemap.$tenantSlug.sitemap[.]xml'
import { Route as ApiPublicFeedsTenantSlugVrsyncDotxmlRouteImport } from './routes/api.public.feeds.$tenantSlug.vrsync[.]xml'
import { Route as ApiPublicFeedsTenantSlugOlxDotxmlRouteImport } from './routes/api.public.feeds.$tenantSlug.olx[.]xml'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasBuscasRoute = MinhasBuscasRouteImport.update({
  id: '/minhas-buscas',
  path: '/minhas-buscas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraMudancaRoute = CalculadoraMudancaRouteImport.update({
  id: '/calculadora-mudanca',
  path: '/calculadora-mudanca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraItbiRoute = CalculadoraItbiRouteImport.update({
  id: '/calculadora-itbi',
  path: '/calculadora-itbi',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraFinanciamentoRoute =
  CalculadoraFinanciamentoRouteImport.update({
    id: '/calculadora-financiamento',
    path: '/calculadora-financiamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaIndexRoute = ContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContaRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VisitaCheckinTokenRoute = VisitaCheckinTokenRouteImport.update({
  id: '/visita-checkin/$token',
  path: '/visita-checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroAnunciarTenantSlugRoute = QueroAnunciarTenantSlugRouteImport.update({
  id: '/quero-anunciar/$tenantSlug',
  path: '/quero-anunciar/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelSlugRoute = ImovelSlugRouteImport.update({
  id: '/imovel/$slug',
  path: '/imovel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const CorretorSlugRoute = CorretorSlugRouteImport.update({
  id: '/corretor/$slug',
  path: '/corretor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaVisitasRoute = ContaVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => ContaRoute,
} as any)
const ContaPerfilRoute = ContaPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => ContaRoute,
} as any)
const ContaFavoritosRoute = ContaFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => ContaRoute,
} as any)
const ContaBuscasRoute = ContaBuscasRouteImport.update({
  id: '/buscas',
  path: '/buscas',
  getParentRoute: () => ContaRoute,
} as any)
const AvaliacaoTenantSlugRoute = AvaliacaoTenantSlugRouteImport.update({
  id: '/avaliacao/$tenantSlug',
  path: '/avaliacao/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVisitasRoute = AppVisitasRouteImport.update({
  id: '/visitas',
  path: '/visitas',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPortaisRoute = AppPortaisRouteImport.update({
  id: '/portais',
  path: '/portais',
  getParentRoute: () => AppRoute,
} as any)
const AppEncurtadorRoute = AppEncurtadorRouteImport.update({
  id: '/encurtador',
  path: '/encurtador',
  getParentRoute: () => AppRoute,
} as any)
const AppContratacaoRoute = AppContratacaoRouteImport.update({
  id: '/contratacao',
  path: '/contratacao',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoriosRoute = AppCartoriosRouteImport.update({
  id: '/cartorios',
  path: '/cartorios',
  getParentRoute: () => AppRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanosRoute = AdminPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulosRoute = AdminModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLimitesRoute = AdminLimitesRouteImport.update({
  id: '/limites',
  path: '/limites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const ContaChatIndexRoute = ContaChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ContaRoute,
} as any)
const AppSiteIndexRoute = AppSiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppLocacaoIndexRoute = AppLocacaoIndexRouteImport.update({
  id: '/locacao/',
  path: '/locacao/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIndexRoute = AppImoveisIndexRouteImport.update({
  id: '/imoveis/',
  path: '/imoveis/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIndexRoute = AppFinanceiroIndexRouteImport.update({
  id: '/financeiro/',
  path: '/financeiro/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpreendimentosIndexRoute = AppEmpreendimentosIndexRouteImport.update({
  id: '/empreendimentos/',
  path: '/empreendimentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresIndexRoute = AppCorretoresIndexRouteImport.update({
  id: '/corretores/',
  path: '/corretores/',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosIndexRoute = AppContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppComissoesIndexRoute = AppComissoesIndexRouteImport.update({
  id: '/comissoes/',
  path: '/comissoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const ContaChatIdRoute = ContaChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => ContaRoute,
} as any)
const AppSiteWidgetsRoute = AppSiteWidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppSiteBlogRoute = AppSiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AppSiteRoute,
} as any)
const AppLeadsConfiguracaoRoute = AppLeadsConfiguracaoRouteImport.update({
  id: '/leads/configuracao',
  path: '/leads/configuracao',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsIdRoute = AppLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisNovoRoute = AppImoveisNovoRouteImport.update({
  id: '/imoveis/novo',
  path: '/imoveis/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisCompararRoute = AppImoveisCompararRouteImport.update({
  id: '/imoveis/comparar',
  path: '/imoveis/comparar',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisIdRoute = AppImoveisIdRouteImport.update({
  id: '/imoveis/$id',
  path: '/imoveis/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroNovoRoute = AppFinanceiroNovoRouteImport.update({
  id: '/financeiro/novo',
  path: '/financeiro/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroIdRoute = AppFinanceiroIdRouteImport.update({
  id: '/financeiro/$id',
  path: '/financeiro/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpreendimentosIdRoute = AppEmpreendimentosIdRouteImport.update({
  id: '/empreendimentos/$id',
  path: '/empreendimentos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresNovoRoute = AppCorretoresNovoRouteImport.update({
  id: '/corretores/novo',
  path: '/corretores/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresIdRoute = AppCorretoresIdRouteImport.update({
  id: '/corretores/$id',
  path: '/corretores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosNovoRoute = AppContratosNovoRouteImport.update({
  id: '/contratos/novo',
  path: '/contratos/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosModelosRoute = AppContratosModelosRouteImport.update({
  id: '/contratos/modelos',
  path: '/contratos/modelos',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosIdRoute = AppContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesWebhooksRoute =
  AppConfiguracoesWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesSegurancaRoute =
  AppConfiguracoesSegurancaRouteImport.update({
    id: '/seguranca',
    path: '/seguranca',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesScoringRoute = AppConfiguracoesScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesPrivacidadeRoute =
  AppConfiguracoesPrivacidadeRouteImport.update({
    id: '/privacidade',
    path: '/privacidade',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesPlanoContasRoute =
  AppConfiguracoesPlanoContasRouteImport.update({
    id: '/plano-contas',
    path: '/plano-contas',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesNotificacoesRoute =
  AppConfiguracoesNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesModulosRoute = AppConfiguracoesModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesImportarRoute =
  AppConfiguracoesImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesImobiliariaRoute =
  AppConfiguracoesImobiliariaRouteImport.update({
    id: '/imobiliaria',
    path: '/imobiliaria',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesGoliveRoute = AppConfiguracoesGoliveRouteImport.update({
  id: '/golive',
  path: '/golive',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesFunisRoute = AppConfiguracoesFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesEquipeRoute = AppConfiguracoesEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesDominiosRoute =
  AppConfiguracoesDominiosRouteImport.update({
    id: '/dominios',
    path: '/dominios',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesChecklistRoute =
  AppConfiguracoesChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesCentrosCustoRoute =
  AppConfiguracoesCentrosCustoRouteImport.update({
    id: '/centros-custo',
    path: '/centros-custo',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesCamposRoute = AppConfiguracoesCamposRouteImport.update({
  id: '/campos',
  path: '/campos',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesCadenciasRoute =
  AppConfiguracoesCadenciasRouteImport.update({
    id: '/cadencias',
    path: '/cadencias',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesBrandingRoute =
  AppConfiguracoesBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesApiRoute = AppConfiguracoesApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugPPageSlugRoute = SiteSlugPPageSlugRouteImport.update({
  id: '/p/$pageSlug',
  path: '/p/$pageSlug',
  getParentRoute: () => SiteSlugRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContratosIdImprimirRoute = AppContratosIdImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => AppContratosIdRoute,
} as any)
const ApiPublicWebhooksDeliverRoute =
  ApiPublicWebhooksDeliverRouteImport.update({
    id: '/api/public/webhooks/deliver',
    path: '/api/public/webhooks/deliver',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1LeadsRoute = ApiPublicV1LeadsRouteImport.update({
  id: '/api/public/v1/leads',
  path: '/api/public/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ImoveisRoute = ApiPublicV1ImoveisRouteImport.update({
  id: '/api/public/v1/imoveis',
  path: '/api/public/v1/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronVisitasNotificacoesRoute =
  ApiPublicCronVisitasNotificacoesRouteImport.update({
    id: '/api/public/cron/visitas-notificacoes',
    path: '/api/public/cron/visitas-notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSnapshotRoute = ApiPublicCronSnapshotRouteImport.update({
  id: '/api/public/cron/snapshot',
  path: '/api/public/cron/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronBuscasAlertasRoute =
  ApiPublicCronBuscasAlertasRouteImport.update({
    id: '/api/public/cron/buscas-alertas',
    path: '/api/public/cron/buscas-alertas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSitemapTenantSlugSitemapDotxmlRoute =
  ApiPublicSitemapTenantSlugSitemapDotxmlRouteImport.update({
    id: '/api/public/sitemap/$tenantSlug/sitemap.xml',
    path: '/api/public/sitemap/$tenantSlug/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsTenantSlugVrsyncDotxmlRoute =
  ApiPublicFeedsTenantSlugVrsyncDotxmlRouteImport.update({
    id: '/api/public/feeds/$tenantSlug/vrsync.xml',
    path: '/api/public/feeds/$tenantSlug/vrsync.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFeedsTenantSlugOlxDotxmlRoute =
  ApiPublicFeedsTenantSlugOlxDotxmlRouteImport.update({
    id: '/api/public/feeds/$tenantSlug/olx.xml',
    path: '/api/public/feeds/$tenantSlug/olx.xml',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/calculadora-financiamento': typeof CalculadoraFinanciamentoRoute
  '/calculadora-itbi': typeof CalculadoraItbiRoute
  '/calculadora-mudanca': typeof CalculadoraMudancaRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRoute
  '/conta': typeof ContaRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minhas-buscas': typeof MinhasBuscasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/cartorios': typeof AppCartoriosRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/contratacao': typeof AppContratacaoRoute
  '/app/encurtador': typeof AppEncurtadorRoute
  '/app/portais': typeof AppPortaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/site': typeof AppSiteRouteWithChildren
  '/app/tarefas': typeof AppTarefasRoute
  '/app/visitas': typeof AppVisitasRoute
  '/avaliacao/$tenantSlug': typeof AvaliacaoTenantSlugRoute
  '/conta/buscas': typeof ContaBuscasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/visitas': typeof ContaVisitasRoute
  '/corretor/$slug': typeof CorretorSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/quero-anunciar/$tenantSlug': typeof QueroAnunciarTenantSlugRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/visita-checkin/$token': typeof VisitaCheckinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/configuracoes/api': typeof AppConfiguracoesApiRoute
  '/app/configuracoes/branding': typeof AppConfiguracoesBrandingRoute
  '/app/configuracoes/cadencias': typeof AppConfiguracoesCadenciasRoute
  '/app/configuracoes/campos': typeof AppConfiguracoesCamposRoute
  '/app/configuracoes/centros-custo': typeof AppConfiguracoesCentrosCustoRoute
  '/app/configuracoes/checklist': typeof AppConfiguracoesChecklistRoute
  '/app/configuracoes/dominios': typeof AppConfiguracoesDominiosRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/funis': typeof AppConfiguracoesFunisRoute
  '/app/configuracoes/golive': typeof AppConfiguracoesGoliveRoute
  '/app/configuracoes/imobiliaria': typeof AppConfiguracoesImobiliariaRoute
  '/app/configuracoes/importar': typeof AppConfiguracoesImportarRoute
  '/app/configuracoes/modulos': typeof AppConfiguracoesModulosRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/plano-contas': typeof AppConfiguracoesPlanoContasRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/configuracoes/scoring': typeof AppConfiguracoesScoringRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/configuracoes/webhooks': typeof AppConfiguracoesWebhooksRoute
  '/app/contratos/$id': typeof AppContratosIdRouteWithChildren
  '/app/contratos/modelos': typeof AppContratosModelosRoute
  '/app/contratos/novo': typeof AppContratosNovoRoute
  '/app/corretores/$id': typeof AppCorretoresIdRoute
  '/app/corretores/novo': typeof AppCorretoresNovoRoute
  '/app/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/app/financeiro/$id': typeof AppFinanceiroIdRoute
  '/app/financeiro/novo': typeof AppFinanceiroNovoRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis/comparar': typeof AppImoveisCompararRoute
  '/app/imoveis/novo': typeof AppImoveisNovoRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/leads/configuracao': typeof AppLeadsConfiguracaoRoute
  '/app/site/blog': typeof AppSiteBlogRoute
  '/app/site/widgets': typeof AppSiteWidgetsRoute
  '/conta/chat/$id': typeof ContaChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/comissoes/': typeof AppComissoesIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/contratos/': typeof AppContratosIndexRoute
  '/app/corretores/': typeof AppCorretoresIndexRoute
  '/app/empreendimentos/': typeof AppEmpreendimentosIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/locacao/': typeof AppLocacaoIndexRoute
  '/app/site/': typeof AppSiteIndexRoute
  '/conta/chat/': typeof ContaChatIndexRoute
  '/api/public/cron/buscas-alertas': typeof ApiPublicCronBuscasAlertasRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
  '/api/public/cron/visitas-notificacoes': typeof ApiPublicCronVisitasNotificacoesRoute
  '/api/public/v1/imoveis': typeof ApiPublicV1ImoveisRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/webhooks/deliver': typeof ApiPublicWebhooksDeliverRoute
  '/app/contratos/$id/imprimir': typeof AppContratosIdImprimirRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/site/$slug/p/$pageSlug': typeof SiteSlugPPageSlugRoute
  '/api/public/feeds/$tenantSlug/olx.xml': typeof ApiPublicFeedsTenantSlugOlxDotxmlRoute
  '/api/public/feeds/$tenantSlug/vrsync.xml': typeof ApiPublicFeedsTenantSlugVrsyncDotxmlRoute
  '/api/public/sitemap/$tenantSlug/sitemap.xml': typeof ApiPublicSitemapTenantSlugSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/calculadora-financiamento': typeof CalculadoraFinanciamentoRoute
  '/calculadora-itbi': typeof CalculadoraItbiRoute
  '/calculadora-mudanca': typeof CalculadoraMudancaRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRoute
  '/favoritos': typeof FavoritosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minhas-buscas': typeof MinhasBuscasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/cartorios': typeof AppCartoriosRoute
  '/app/contratacao': typeof AppContratacaoRoute
  '/app/encurtador': typeof AppEncurtadorRoute
  '/app/portais': typeof AppPortaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/tarefas': typeof AppTarefasRoute
  '/app/visitas': typeof AppVisitasRoute
  '/avaliacao/$tenantSlug': typeof AvaliacaoTenantSlugRoute
  '/conta/buscas': typeof ContaBuscasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/visitas': typeof ContaVisitasRoute
  '/corretor/$slug': typeof CorretorSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/quero-anunciar/$tenantSlug': typeof QueroAnunciarTenantSlugRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/visita-checkin/$token': typeof VisitaCheckinTokenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/conta': typeof ContaIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/configuracoes/api': typeof AppConfiguracoesApiRoute
  '/app/configuracoes/branding': typeof AppConfiguracoesBrandingRoute
  '/app/configuracoes/cadencias': typeof AppConfiguracoesCadenciasRoute
  '/app/configuracoes/campos': typeof AppConfiguracoesCamposRoute
  '/app/configuracoes/centros-custo': typeof AppConfiguracoesCentrosCustoRoute
  '/app/configuracoes/checklist': typeof AppConfiguracoesChecklistRoute
  '/app/configuracoes/dominios': typeof AppConfiguracoesDominiosRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/funis': typeof AppConfiguracoesFunisRoute
  '/app/configuracoes/golive': typeof AppConfiguracoesGoliveRoute
  '/app/configuracoes/imobiliaria': typeof AppConfiguracoesImobiliariaRoute
  '/app/configuracoes/importar': typeof AppConfiguracoesImportarRoute
  '/app/configuracoes/modulos': typeof AppConfiguracoesModulosRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/plano-contas': typeof AppConfiguracoesPlanoContasRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/configuracoes/scoring': typeof AppConfiguracoesScoringRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/configuracoes/webhooks': typeof AppConfiguracoesWebhooksRoute
  '/app/contratos/$id': typeof AppContratosIdRouteWithChildren
  '/app/contratos/modelos': typeof AppContratosModelosRoute
  '/app/contratos/novo': typeof AppContratosNovoRoute
  '/app/corretores/$id': typeof AppCorretoresIdRoute
  '/app/corretores/novo': typeof AppCorretoresNovoRoute
  '/app/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/app/financeiro/$id': typeof AppFinanceiroIdRoute
  '/app/financeiro/novo': typeof AppFinanceiroNovoRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis/comparar': typeof AppImoveisCompararRoute
  '/app/imoveis/novo': typeof AppImoveisNovoRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/leads/configuracao': typeof AppLeadsConfiguracaoRoute
  '/app/site/blog': typeof AppSiteBlogRoute
  '/app/site/widgets': typeof AppSiteWidgetsRoute
  '/conta/chat/$id': typeof ContaChatIdRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/comissoes': typeof AppComissoesIndexRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/contratos': typeof AppContratosIndexRoute
  '/app/corretores': typeof AppCorretoresIndexRoute
  '/app/empreendimentos': typeof AppEmpreendimentosIndexRoute
  '/app/financeiro': typeof AppFinanceiroIndexRoute
  '/app/imoveis': typeof AppImoveisIndexRoute
  '/app/leads': typeof AppLeadsIndexRoute
  '/app/locacao': typeof AppLocacaoIndexRoute
  '/app/site': typeof AppSiteIndexRoute
  '/conta/chat': typeof ContaChatIndexRoute
  '/api/public/cron/buscas-alertas': typeof ApiPublicCronBuscasAlertasRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
  '/api/public/cron/visitas-notificacoes': typeof ApiPublicCronVisitasNotificacoesRoute
  '/api/public/v1/imoveis': typeof ApiPublicV1ImoveisRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/webhooks/deliver': typeof ApiPublicWebhooksDeliverRoute
  '/app/contratos/$id/imprimir': typeof AppContratosIdImprimirRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/site/$slug/p/$pageSlug': typeof SiteSlugPPageSlugRoute
  '/api/public/feeds/$tenantSlug/olx.xml': typeof ApiPublicFeedsTenantSlugOlxDotxmlRoute
  '/api/public/feeds/$tenantSlug/vrsync.xml': typeof ApiPublicFeedsTenantSlugVrsyncDotxmlRoute
  '/api/public/sitemap/$tenantSlug/sitemap.xml': typeof ApiPublicSitemapTenantSlugSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/calculadora-financiamento': typeof CalculadoraFinanciamentoRoute
  '/calculadora-itbi': typeof CalculadoraItbiRoute
  '/calculadora-mudanca': typeof CalculadoraMudancaRoute
  '/calculadoras': typeof CalculadorasRoute
  '/comparar': typeof CompararRoute
  '/conta': typeof ContaRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/lgpd': typeof LgpdRoute
  '/login': typeof LoginRoute
  '/minhas-buscas': typeof MinhasBuscasRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/limites': typeof AdminLimitesRoute
  '/admin/modulos': typeof AdminModulosRoute
  '/admin/planos': typeof AdminPlanosRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/cartorios': typeof AppCartoriosRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/contratacao': typeof AppContratacaoRoute
  '/app/encurtador': typeof AppEncurtadorRoute
  '/app/portais': typeof AppPortaisRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/site': typeof AppSiteRouteWithChildren
  '/app/tarefas': typeof AppTarefasRoute
  '/app/visitas': typeof AppVisitasRoute
  '/avaliacao/$tenantSlug': typeof AvaliacaoTenantSlugRoute
  '/conta/buscas': typeof ContaBuscasRoute
  '/conta/favoritos': typeof ContaFavoritosRoute
  '/conta/perfil': typeof ContaPerfilRoute
  '/conta/visitas': typeof ContaVisitasRoute
  '/corretor/$slug': typeof CorretorSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/imovel/$slug': typeof ImovelSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/quero-anunciar/$tenantSlug': typeof QueroAnunciarTenantSlugRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/visita-checkin/$token': typeof VisitaCheckinTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/conta/': typeof ContaIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/configuracoes/api': typeof AppConfiguracoesApiRoute
  '/app/configuracoes/branding': typeof AppConfiguracoesBrandingRoute
  '/app/configuracoes/cadencias': typeof AppConfiguracoesCadenciasRoute
  '/app/configuracoes/campos': typeof AppConfiguracoesCamposRoute
  '/app/configuracoes/centros-custo': typeof AppConfiguracoesCentrosCustoRoute
  '/app/configuracoes/checklist': typeof AppConfiguracoesChecklistRoute
  '/app/configuracoes/dominios': typeof AppConfiguracoesDominiosRoute
  '/app/configuracoes/equipe': typeof AppConfiguracoesEquipeRoute
  '/app/configuracoes/funis': typeof AppConfiguracoesFunisRoute
  '/app/configuracoes/golive': typeof AppConfiguracoesGoliveRoute
  '/app/configuracoes/imobiliaria': typeof AppConfiguracoesImobiliariaRoute
  '/app/configuracoes/importar': typeof AppConfiguracoesImportarRoute
  '/app/configuracoes/modulos': typeof AppConfiguracoesModulosRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/plano-contas': typeof AppConfiguracoesPlanoContasRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/configuracoes/scoring': typeof AppConfiguracoesScoringRoute
  '/app/configuracoes/seguranca': typeof AppConfiguracoesSegurancaRoute
  '/app/configuracoes/webhooks': typeof AppConfiguracoesWebhooksRoute
  '/app/contratos/$id': typeof AppContratosIdRouteWithChildren
  '/app/contratos/modelos': typeof AppContratosModelosRoute
  '/app/contratos/novo': typeof AppContratosNovoRoute
  '/app/corretores/$id': typeof AppCorretoresIdRoute
  '/app/corretores/novo': typeof AppCorretoresNovoRoute
  '/app/empreendimentos/$id': typeof AppEmpreendimentosIdRoute
  '/app/financeiro/$id': typeof AppFinanceiroIdRoute
  '/app/financeiro/novo': typeof AppFinanceiroNovoRoute
  '/app/imoveis/$id': typeof AppImoveisIdRoute
  '/app/imoveis/comparar': typeof AppImoveisCompararRoute
  '/app/imoveis/novo': typeof AppImoveisNovoRoute
  '/app/leads/$id': typeof AppLeadsIdRoute
  '/app/leads/configuracao': typeof AppLeadsConfiguracaoRoute
  '/app/site/blog': typeof AppSiteBlogRoute
  '/app/site/widgets': typeof AppSiteWidgetsRoute
  '/conta/chat/$id': typeof ContaChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/comissoes/': typeof AppComissoesIndexRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/contratos/': typeof AppContratosIndexRoute
  '/app/corretores/': typeof AppCorretoresIndexRoute
  '/app/empreendimentos/': typeof AppEmpreendimentosIndexRoute
  '/app/financeiro/': typeof AppFinanceiroIndexRoute
  '/app/imoveis/': typeof AppImoveisIndexRoute
  '/app/leads/': typeof AppLeadsIndexRoute
  '/app/locacao/': typeof AppLocacaoIndexRoute
  '/app/site/': typeof AppSiteIndexRoute
  '/conta/chat/': typeof ContaChatIndexRoute
  '/api/public/cron/buscas-alertas': typeof ApiPublicCronBuscasAlertasRoute
  '/api/public/cron/snapshot': typeof ApiPublicCronSnapshotRoute
  '/api/public/cron/visitas-notificacoes': typeof ApiPublicCronVisitasNotificacoesRoute
  '/api/public/v1/imoveis': typeof ApiPublicV1ImoveisRoute
  '/api/public/v1/leads': typeof ApiPublicV1LeadsRoute
  '/api/public/webhooks/deliver': typeof ApiPublicWebhooksDeliverRoute
  '/app/contratos/$id/imprimir': typeof AppContratosIdImprimirRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/site/$slug/p/$pageSlug': typeof SiteSlugPPageSlugRoute
  '/api/public/feeds/$tenantSlug/olx.xml': typeof ApiPublicFeedsTenantSlugOlxDotxmlRoute
  '/api/public/feeds/$tenantSlug/vrsync.xml': typeof ApiPublicFeedsTenantSlugVrsyncDotxmlRoute
  '/api/public/sitemap/$tenantSlug/sitemap.xml': typeof ApiPublicSitemapTenantSlugSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/buscar'
    | '/calculadora-financiamento'
    | '/calculadora-itbi'
    | '/calculadora-mudanca'
    | '/calculadoras'
    | '/comparar'
    | '/conta'
    | '/favoritos'
    | '/lgpd'
    | '/login'
    | '/minhas-buscas'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/status'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/emails'
    | '/admin/flags'
    | '/admin/integracoes'
    | '/admin/limites'
    | '/admin/modulos'
    | '/admin/planos'
    | '/admin/tenants'
    | '/app/cartorios'
    | '/app/configuracoes'
    | '/app/contratacao'
    | '/app/encurtador'
    | '/app/portais'
    | '/app/relatorios'
    | '/app/site'
    | '/app/tarefas'
    | '/app/visitas'
    | '/avaliacao/$tenantSlug'
    | '/conta/buscas'
    | '/conta/favoritos'
    | '/conta/perfil'
    | '/conta/visitas'
    | '/corretor/$slug'
    | '/docs/api'
    | '/imovel/$slug'
    | '/l/$slug'
    | '/quero-anunciar/$tenantSlug'
    | '/site/$slug'
    | '/visita-checkin/$token'
    | '/admin/'
    | '/app/'
    | '/conta/'
    | '/api/public/health'
    | '/app/chat/$id'
    | '/app/configuracoes/api'
    | '/app/configuracoes/branding'
    | '/app/configuracoes/cadencias'
    | '/app/configuracoes/campos'
    | '/app/configuracoes/centros-custo'
    | '/app/configuracoes/checklist'
    | '/app/configuracoes/dominios'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/funis'
    | '/app/configuracoes/golive'
    | '/app/configuracoes/imobiliaria'
    | '/app/configuracoes/importar'
    | '/app/configuracoes/modulos'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/plano-contas'
    | '/app/configuracoes/privacidade'
    | '/app/configuracoes/scoring'
    | '/app/configuracoes/seguranca'
    | '/app/configuracoes/webhooks'
    | '/app/contratos/$id'
    | '/app/contratos/modelos'
    | '/app/contratos/novo'
    | '/app/corretores/$id'
    | '/app/corretores/novo'
    | '/app/empreendimentos/$id'
    | '/app/financeiro/$id'
    | '/app/financeiro/novo'
    | '/app/imoveis/$id'
    | '/app/imoveis/comparar'
    | '/app/imoveis/novo'
    | '/app/leads/$id'
    | '/app/leads/configuracao'
    | '/app/site/blog'
    | '/app/site/widgets'
    | '/conta/chat/$id'
    | '/app/chat/'
    | '/app/comissoes/'
    | '/app/configuracoes/'
    | '/app/contratos/'
    | '/app/corretores/'
    | '/app/empreendimentos/'
    | '/app/financeiro/'
    | '/app/imoveis/'
    | '/app/leads/'
    | '/app/locacao/'
    | '/app/site/'
    | '/conta/chat/'
    | '/api/public/cron/buscas-alertas'
    | '/api/public/cron/snapshot'
    | '/api/public/cron/visitas-notificacoes'
    | '/api/public/v1/imoveis'
    | '/api/public/v1/leads'
    | '/api/public/webhooks/deliver'
    | '/app/contratos/$id/imprimir'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/site/$slug/p/$pageSlug'
    | '/api/public/feeds/$tenantSlug/olx.xml'
    | '/api/public/feeds/$tenantSlug/vrsync.xml'
    | '/api/public/sitemap/$tenantSlug/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/calculadora-financiamento'
    | '/calculadora-itbi'
    | '/calculadora-mudanca'
    | '/calculadoras'
    | '/comparar'
    | '/favoritos'
    | '/lgpd'
    | '/login'
    | '/minhas-buscas'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/status'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/emails'
    | '/admin/flags'
    | '/admin/integracoes'
    | '/admin/limites'
    | '/admin/modulos'
    | '/admin/planos'
    | '/admin/tenants'
    | '/app/cartorios'
    | '/app/contratacao'
    | '/app/encurtador'
    | '/app/portais'
    | '/app/relatorios'
    | '/app/tarefas'
    | '/app/visitas'
    | '/avaliacao/$tenantSlug'
    | '/conta/buscas'
    | '/conta/favoritos'
    | '/conta/perfil'
    | '/conta/visitas'
    | '/corretor/$slug'
    | '/docs/api'
    | '/imovel/$slug'
    | '/l/$slug'
    | '/quero-anunciar/$tenantSlug'
    | '/site/$slug'
    | '/visita-checkin/$token'
    | '/admin'
    | '/app'
    | '/conta'
    | '/api/public/health'
    | '/app/chat/$id'
    | '/app/configuracoes/api'
    | '/app/configuracoes/branding'
    | '/app/configuracoes/cadencias'
    | '/app/configuracoes/campos'
    | '/app/configuracoes/centros-custo'
    | '/app/configuracoes/checklist'
    | '/app/configuracoes/dominios'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/funis'
    | '/app/configuracoes/golive'
    | '/app/configuracoes/imobiliaria'
    | '/app/configuracoes/importar'
    | '/app/configuracoes/modulos'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/plano-contas'
    | '/app/configuracoes/privacidade'
    | '/app/configuracoes/scoring'
    | '/app/configuracoes/seguranca'
    | '/app/configuracoes/webhooks'
    | '/app/contratos/$id'
    | '/app/contratos/modelos'
    | '/app/contratos/novo'
    | '/app/corretores/$id'
    | '/app/corretores/novo'
    | '/app/empreendimentos/$id'
    | '/app/financeiro/$id'
    | '/app/financeiro/novo'
    | '/app/imoveis/$id'
    | '/app/imoveis/comparar'
    | '/app/imoveis/novo'
    | '/app/leads/$id'
    | '/app/leads/configuracao'
    | '/app/site/blog'
    | '/app/site/widgets'
    | '/conta/chat/$id'
    | '/app/chat'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/corretores'
    | '/app/empreendimentos'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/leads'
    | '/app/locacao'
    | '/app/site'
    | '/conta/chat'
    | '/api/public/cron/buscas-alertas'
    | '/api/public/cron/snapshot'
    | '/api/public/cron/visitas-notificacoes'
    | '/api/public/v1/imoveis'
    | '/api/public/v1/leads'
    | '/api/public/webhooks/deliver'
    | '/app/contratos/$id/imprimir'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/site/$slug/p/$pageSlug'
    | '/api/public/feeds/$tenantSlug/olx.xml'
    | '/api/public/feeds/$tenantSlug/vrsync.xml'
    | '/api/public/sitemap/$tenantSlug/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/buscar'
    | '/calculadora-financiamento'
    | '/calculadora-itbi'
    | '/calculadora-mudanca'
    | '/calculadoras'
    | '/comparar'
    | '/conta'
    | '/favoritos'
    | '/lgpd'
    | '/login'
    | '/minhas-buscas'
    | '/planos'
    | '/privacidade'
    | '/reset-password'
    | '/robots.txt'
    | '/signup'
    | '/status'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/emails'
    | '/admin/flags'
    | '/admin/integracoes'
    | '/admin/limites'
    | '/admin/modulos'
    | '/admin/planos'
    | '/admin/tenants'
    | '/app/cartorios'
    | '/app/configuracoes'
    | '/app/contratacao'
    | '/app/encurtador'
    | '/app/portais'
    | '/app/relatorios'
    | '/app/site'
    | '/app/tarefas'
    | '/app/visitas'
    | '/avaliacao/$tenantSlug'
    | '/conta/buscas'
    | '/conta/favoritos'
    | '/conta/perfil'
    | '/conta/visitas'
    | '/corretor/$slug'
    | '/docs/api'
    | '/imovel/$slug'
    | '/l/$slug'
    | '/quero-anunciar/$tenantSlug'
    | '/site/$slug'
    | '/visita-checkin/$token'
    | '/admin/'
    | '/app/'
    | '/conta/'
    | '/api/public/health'
    | '/app/chat/$id'
    | '/app/configuracoes/api'
    | '/app/configuracoes/branding'
    | '/app/configuracoes/cadencias'
    | '/app/configuracoes/campos'
    | '/app/configuracoes/centros-custo'
    | '/app/configuracoes/checklist'
    | '/app/configuracoes/dominios'
    | '/app/configuracoes/equipe'
    | '/app/configuracoes/funis'
    | '/app/configuracoes/golive'
    | '/app/configuracoes/imobiliaria'
    | '/app/configuracoes/importar'
    | '/app/configuracoes/modulos'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/plano-contas'
    | '/app/configuracoes/privacidade'
    | '/app/configuracoes/scoring'
    | '/app/configuracoes/seguranca'
    | '/app/configuracoes/webhooks'
    | '/app/contratos/$id'
    | '/app/contratos/modelos'
    | '/app/contratos/novo'
    | '/app/corretores/$id'
    | '/app/corretores/novo'
    | '/app/empreendimentos/$id'
    | '/app/financeiro/$id'
    | '/app/financeiro/novo'
    | '/app/imoveis/$id'
    | '/app/imoveis/comparar'
    | '/app/imoveis/novo'
    | '/app/leads/$id'
    | '/app/leads/configuracao'
    | '/app/site/blog'
    | '/app/site/widgets'
    | '/conta/chat/$id'
    | '/app/chat/'
    | '/app/comissoes/'
    | '/app/configuracoes/'
    | '/app/contratos/'
    | '/app/corretores/'
    | '/app/empreendimentos/'
    | '/app/financeiro/'
    | '/app/imoveis/'
    | '/app/leads/'
    | '/app/locacao/'
    | '/app/site/'
    | '/conta/chat/'
    | '/api/public/cron/buscas-alertas'
    | '/api/public/cron/snapshot'
    | '/api/public/cron/visitas-notificacoes'
    | '/api/public/v1/imoveis'
    | '/api/public/v1/leads'
    | '/api/public/webhooks/deliver'
    | '/app/contratos/$id/imprimir'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/site/$slug/p/$pageSlug'
    | '/api/public/feeds/$tenantSlug/olx.xml'
    | '/api/public/feeds/$tenantSlug/vrsync.xml'
    | '/api/public/sitemap/$tenantSlug/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  CalculadoraFinanciamentoRoute: typeof CalculadoraFinanciamentoRoute
  CalculadoraItbiRoute: typeof CalculadoraItbiRoute
  CalculadoraMudancaRoute: typeof CalculadoraMudancaRoute
  CalculadorasRoute: typeof CalculadorasRoute
  CompararRoute: typeof CompararRoute
  ContaRoute: typeof ContaRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  LgpdRoute: typeof LgpdRoute
  LoginRoute: typeof LoginRoute
  MinhasBuscasRoute: typeof MinhasBuscasRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  TermosRoute: typeof TermosRoute
  AvaliacaoTenantSlugRoute: typeof AvaliacaoTenantSlugRoute
  CorretorSlugRoute: typeof CorretorSlugRoute
  DocsApiRoute: typeof DocsApiRoute
  ImovelSlugRoute: typeof ImovelSlugRoute
  LSlugRoute: typeof LSlugRoute
  QueroAnunciarTenantSlugRoute: typeof QueroAnunciarTenantSlugRoute
  SiteSlugRoute: typeof SiteSlugRouteWithChildren
  VisitaCheckinTokenRoute: typeof VisitaCheckinTokenRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicCronBuscasAlertasRoute: typeof ApiPublicCronBuscasAlertasRoute
  ApiPublicCronSnapshotRoute: typeof ApiPublicCronSnapshotRoute
  ApiPublicCronVisitasNotificacoesRoute: typeof ApiPublicCronVisitasNotificacoesRoute
  ApiPublicV1ImoveisRoute: typeof ApiPublicV1ImoveisRoute
  ApiPublicV1LeadsRoute: typeof ApiPublicV1LeadsRoute
  ApiPublicWebhooksDeliverRoute: typeof ApiPublicWebhooksDeliverRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicFeedsTenantSlugOlxDotxmlRoute: typeof ApiPublicFeedsTenantSlugOlxDotxmlRoute
  ApiPublicFeedsTenantSlugVrsyncDotxmlRoute: typeof ApiPublicFeedsTenantSlugVrsyncDotxmlRoute
  ApiPublicSitemapTenantSlugSitemapDotxmlRoute: typeof ApiPublicSitemapTenantSlugSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-buscas': {
      id: '/minhas-buscas'
      path: '/minhas-buscas'
      fullPath: '/minhas-buscas'
      preLoaderRoute: typeof MinhasBuscasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-mudanca': {
      id: '/calculadora-mudanca'
      path: '/calculadora-mudanca'
      fullPath: '/calculadora-mudanca'
      preLoaderRoute: typeof CalculadoraMudancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-itbi': {
      id: '/calculadora-itbi'
      path: '/calculadora-itbi'
      fullPath: '/calculadora-itbi'
      preLoaderRoute: typeof CalculadoraItbiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-financiamento': {
      id: '/calculadora-financiamento'
      path: '/calculadora-financiamento'
      fullPath: '/calculadora-financiamento'
      preLoaderRoute: typeof CalculadoraFinanciamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/': {
      id: '/conta/'
      path: '/'
      fullPath: '/conta/'
      preLoaderRoute: typeof ContaIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/visita-checkin/$token': {
      id: '/visita-checkin/$token'
      path: '/visita-checkin/$token'
      fullPath: '/visita-checkin/$token'
      preLoaderRoute: typeof VisitaCheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero-anunciar/$tenantSlug': {
      id: '/quero-anunciar/$tenantSlug'
      path: '/quero-anunciar/$tenantSlug'
      fullPath: '/quero-anunciar/$tenantSlug'
      preLoaderRoute: typeof QueroAnunciarTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$slug': {
      id: '/imovel/$slug'
      path: '/imovel/$slug'
      fullPath: '/imovel/$slug'
      preLoaderRoute: typeof ImovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corretor/$slug': {
      id: '/corretor/$slug'
      path: '/corretor/$slug'
      fullPath: '/corretor/$slug'
      preLoaderRoute: typeof CorretorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta/visitas': {
      id: '/conta/visitas'
      path: '/visitas'
      fullPath: '/conta/visitas'
      preLoaderRoute: typeof ContaVisitasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/perfil': {
      id: '/conta/perfil'
      path: '/perfil'
      fullPath: '/conta/perfil'
      preLoaderRoute: typeof ContaPerfilRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/favoritos': {
      id: '/conta/favoritos'
      path: '/favoritos'
      fullPath: '/conta/favoritos'
      preLoaderRoute: typeof ContaFavoritosRouteImport
      parentRoute: typeof ContaRoute
    }
    '/conta/buscas': {
      id: '/conta/buscas'
      path: '/buscas'
      fullPath: '/conta/buscas'
      preLoaderRoute: typeof ContaBuscasRouteImport
      parentRoute: typeof ContaRoute
    }
    '/avaliacao/$tenantSlug': {
      id: '/avaliacao/$tenantSlug'
      path: '/avaliacao/$tenantSlug'
      fullPath: '/avaliacao/$tenantSlug'
      preLoaderRoute: typeof AvaliacaoTenantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/visitas': {
      id: '/app/visitas'
      path: '/visitas'
      fullPath: '/app/visitas'
      preLoaderRoute: typeof AppVisitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas': {
      id: '/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/site': {
      id: '/app/site'
      path: '/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portais': {
      id: '/app/portais'
      path: '/portais'
      fullPath: '/app/portais'
      preLoaderRoute: typeof AppPortaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/encurtador': {
      id: '/app/encurtador'
      path: '/encurtador'
      fullPath: '/app/encurtador'
      preLoaderRoute: typeof AppEncurtadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratacao': {
      id: '/app/contratacao'
      path: '/contratacao'
      fullPath: '/app/contratacao'
      preLoaderRoute: typeof AppContratacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cartorios': {
      id: '/app/cartorios'
      path: '/cartorios'
      fullPath: '/app/cartorios'
      preLoaderRoute: typeof AppCartoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/planos': {
      id: '/admin/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminPlanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modulos': {
      id: '/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AdminModulosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/limites': {
      id: '/admin/limites'
      path: '/limites'
      fullPath: '/admin/limites'
      preLoaderRoute: typeof AdminLimitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/conta/chat/': {
      id: '/conta/chat/'
      path: '/chat'
      fullPath: '/conta/chat/'
      preLoaderRoute: typeof ContaChatIndexRouteImport
      parentRoute: typeof ContaRoute
    }
    '/app/site/': {
      id: '/app/site/'
      path: '/'
      fullPath: '/app/site/'
      preLoaderRoute: typeof AppSiteIndexRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/app/locacao/': {
      id: '/app/locacao/'
      path: '/locacao'
      fullPath: '/app/locacao/'
      preLoaderRoute: typeof AppLocacaoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/': {
      id: '/app/imoveis/'
      path: '/imoveis'
      fullPath: '/app/imoveis/'
      preLoaderRoute: typeof AppImoveisIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/': {
      id: '/app/financeiro/'
      path: '/financeiro'
      fullPath: '/app/financeiro/'
      preLoaderRoute: typeof AppFinanceiroIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empreendimentos/': {
      id: '/app/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/app/empreendimentos/'
      preLoaderRoute: typeof AppEmpreendimentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores/': {
      id: '/app/corretores/'
      path: '/corretores'
      fullPath: '/app/corretores/'
      preLoaderRoute: typeof AppCorretoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos/': {
      id: '/app/contratos/'
      path: '/contratos'
      fullPath: '/app/contratos/'
      preLoaderRoute: typeof AppContratosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/comissoes/': {
      id: '/app/comissoes/'
      path: '/comissoes'
      fullPath: '/app/comissoes/'
      preLoaderRoute: typeof AppComissoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/conta/chat/$id': {
      id: '/conta/chat/$id'
      path: '/chat/$id'
      fullPath: '/conta/chat/$id'
      preLoaderRoute: typeof ContaChatIdRouteImport
      parentRoute: typeof ContaRoute
    }
    '/app/site/widgets': {
      id: '/app/site/widgets'
      path: '/widgets'
      fullPath: '/app/site/widgets'
      preLoaderRoute: typeof AppSiteWidgetsRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/app/site/blog': {
      id: '/app/site/blog'
      path: '/blog'
      fullPath: '/app/site/blog'
      preLoaderRoute: typeof AppSiteBlogRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/app/leads/configuracao': {
      id: '/app/leads/configuracao'
      path: '/leads/configuracao'
      fullPath: '/app/leads/configuracao'
      preLoaderRoute: typeof AppLeadsConfiguracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/$id': {
      id: '/app/leads/$id'
      path: '/leads/$id'
      fullPath: '/app/leads/$id'
      preLoaderRoute: typeof AppLeadsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/novo': {
      id: '/app/imoveis/novo'
      path: '/imoveis/novo'
      fullPath: '/app/imoveis/novo'
      preLoaderRoute: typeof AppImoveisNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/comparar': {
      id: '/app/imoveis/comparar'
      path: '/imoveis/comparar'
      fullPath: '/app/imoveis/comparar'
      preLoaderRoute: typeof AppImoveisCompararRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis/$id': {
      id: '/app/imoveis/$id'
      path: '/imoveis/$id'
      fullPath: '/app/imoveis/$id'
      preLoaderRoute: typeof AppImoveisIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/novo': {
      id: '/app/financeiro/novo'
      path: '/financeiro/novo'
      fullPath: '/app/financeiro/novo'
      preLoaderRoute: typeof AppFinanceiroNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro/$id': {
      id: '/app/financeiro/$id'
      path: '/financeiro/$id'
      fullPath: '/app/financeiro/$id'
      preLoaderRoute: typeof AppFinanceiroIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empreendimentos/$id': {
      id: '/app/empreendimentos/$id'
      path: '/empreendimentos/$id'
      fullPath: '/app/empreendimentos/$id'
      preLoaderRoute: typeof AppEmpreendimentosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores/novo': {
      id: '/app/corretores/novo'
      path: '/corretores/novo'
      fullPath: '/app/corretores/novo'
      preLoaderRoute: typeof AppCorretoresNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores/$id': {
      id: '/app/corretores/$id'
      path: '/corretores/$id'
      fullPath: '/app/corretores/$id'
      preLoaderRoute: typeof AppCorretoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos/novo': {
      id: '/app/contratos/novo'
      path: '/contratos/novo'
      fullPath: '/app/contratos/novo'
      preLoaderRoute: typeof AppContratosNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos/modelos': {
      id: '/app/contratos/modelos'
      path: '/contratos/modelos'
      fullPath: '/app/contratos/modelos'
      preLoaderRoute: typeof AppContratosModelosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos/$id': {
      id: '/app/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/app/contratos/$id'
      preLoaderRoute: typeof AppContratosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/webhooks': {
      id: '/app/configuracoes/webhooks'
      path: '/webhooks'
      fullPath: '/app/configuracoes/webhooks'
      preLoaderRoute: typeof AppConfiguracoesWebhooksRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/seguranca': {
      id: '/app/configuracoes/seguranca'
      path: '/seguranca'
      fullPath: '/app/configuracoes/seguranca'
      preLoaderRoute: typeof AppConfiguracoesSegurancaRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/scoring': {
      id: '/app/configuracoes/scoring'
      path: '/scoring'
      fullPath: '/app/configuracoes/scoring'
      preLoaderRoute: typeof AppConfiguracoesScoringRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/privacidade': {
      id: '/app/configuracoes/privacidade'
      path: '/privacidade'
      fullPath: '/app/configuracoes/privacidade'
      preLoaderRoute: typeof AppConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/plano-contas': {
      id: '/app/configuracoes/plano-contas'
      path: '/plano-contas'
      fullPath: '/app/configuracoes/plano-contas'
      preLoaderRoute: typeof AppConfiguracoesPlanoContasRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/notificacoes': {
      id: '/app/configuracoes/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/configuracoes/notificacoes'
      preLoaderRoute: typeof AppConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/modulos': {
      id: '/app/configuracoes/modulos'
      path: '/modulos'
      fullPath: '/app/configuracoes/modulos'
      preLoaderRoute: typeof AppConfiguracoesModulosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/importar': {
      id: '/app/configuracoes/importar'
      path: '/importar'
      fullPath: '/app/configuracoes/importar'
      preLoaderRoute: typeof AppConfiguracoesImportarRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/imobiliaria': {
      id: '/app/configuracoes/imobiliaria'
      path: '/imobiliaria'
      fullPath: '/app/configuracoes/imobiliaria'
      preLoaderRoute: typeof AppConfiguracoesImobiliariaRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/golive': {
      id: '/app/configuracoes/golive'
      path: '/golive'
      fullPath: '/app/configuracoes/golive'
      preLoaderRoute: typeof AppConfiguracoesGoliveRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/funis': {
      id: '/app/configuracoes/funis'
      path: '/funis'
      fullPath: '/app/configuracoes/funis'
      preLoaderRoute: typeof AppConfiguracoesFunisRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/equipe': {
      id: '/app/configuracoes/equipe'
      path: '/equipe'
      fullPath: '/app/configuracoes/equipe'
      preLoaderRoute: typeof AppConfiguracoesEquipeRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/dominios': {
      id: '/app/configuracoes/dominios'
      path: '/dominios'
      fullPath: '/app/configuracoes/dominios'
      preLoaderRoute: typeof AppConfiguracoesDominiosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/checklist': {
      id: '/app/configuracoes/checklist'
      path: '/checklist'
      fullPath: '/app/configuracoes/checklist'
      preLoaderRoute: typeof AppConfiguracoesChecklistRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/centros-custo': {
      id: '/app/configuracoes/centros-custo'
      path: '/centros-custo'
      fullPath: '/app/configuracoes/centros-custo'
      preLoaderRoute: typeof AppConfiguracoesCentrosCustoRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/campos': {
      id: '/app/configuracoes/campos'
      path: '/campos'
      fullPath: '/app/configuracoes/campos'
      preLoaderRoute: typeof AppConfiguracoesCamposRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/cadencias': {
      id: '/app/configuracoes/cadencias'
      path: '/cadencias'
      fullPath: '/app/configuracoes/cadencias'
      preLoaderRoute: typeof AppConfiguracoesCadenciasRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/branding': {
      id: '/app/configuracoes/branding'
      path: '/branding'
      fullPath: '/app/configuracoes/branding'
      preLoaderRoute: typeof AppConfiguracoesBrandingRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/api': {
      id: '/app/configuracoes/api'
      path: '/api'
      fullPath: '/app/configuracoes/api'
      preLoaderRoute: typeof AppConfiguracoesApiRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug/p/$pageSlug': {
      id: '/site/$slug/p/$pageSlug'
      path: '/p/$pageSlug'
      fullPath: '/site/$slug/p/$pageSlug'
      preLoaderRoute: typeof SiteSlugPPageSlugRouteImport
      parentRoute: typeof SiteSlugRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/contratos/$id/imprimir': {
      id: '/app/contratos/$id/imprimir'
      path: '/imprimir'
      fullPath: '/app/contratos/$id/imprimir'
      preLoaderRoute: typeof AppContratosIdImprimirRouteImport
      parentRoute: typeof AppContratosIdRoute
    }
    '/api/public/webhooks/deliver': {
      id: '/api/public/webhooks/deliver'
      path: '/api/public/webhooks/deliver'
      fullPath: '/api/public/webhooks/deliver'
      preLoaderRoute: typeof ApiPublicWebhooksDeliverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/leads': {
      id: '/api/public/v1/leads'
      path: '/api/public/v1/leads'
      fullPath: '/api/public/v1/leads'
      preLoaderRoute: typeof ApiPublicV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/imoveis': {
      id: '/api/public/v1/imoveis'
      path: '/api/public/v1/imoveis'
      fullPath: '/api/public/v1/imoveis'
      preLoaderRoute: typeof ApiPublicV1ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/visitas-notificacoes': {
      id: '/api/public/cron/visitas-notificacoes'
      path: '/api/public/cron/visitas-notificacoes'
      fullPath: '/api/public/cron/visitas-notificacoes'
      preLoaderRoute: typeof ApiPublicCronVisitasNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/snapshot': {
      id: '/api/public/cron/snapshot'
      path: '/api/public/cron/snapshot'
      fullPath: '/api/public/cron/snapshot'
      preLoaderRoute: typeof ApiPublicCronSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/buscas-alertas': {
      id: '/api/public/cron/buscas-alertas'
      path: '/api/public/cron/buscas-alertas'
      fullPath: '/api/public/cron/buscas-alertas'
      preLoaderRoute: typeof ApiPublicCronBuscasAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap/$tenantSlug/sitemap.xml': {
      id: '/api/public/sitemap/$tenantSlug/sitemap.xml'
      path: '/api/public/sitemap/$tenantSlug/sitemap.xml'
      fullPath: '/api/public/sitemap/$tenantSlug/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapTenantSlugSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/$tenantSlug/vrsync.xml': {
      id: '/api/public/feeds/$tenantSlug/vrsync.xml'
      path: '/api/public/feeds/$tenantSlug/vrsync.xml'
      fullPath: '/api/public/feeds/$tenantSlug/vrsync.xml'
      preLoaderRoute: typeof ApiPublicFeedsTenantSlugVrsyncDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feeds/$tenantSlug/olx.xml': {
      id: '/api/public/feeds/$tenantSlug/olx.xml'
      path: '/api/public/feeds/$tenantSlug/olx.xml'
      fullPath: '/api/public/feeds/$tenantSlug/olx.xml'
      preLoaderRoute: typeof ApiPublicFeedsTenantSlugOlxDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLimitesRoute: typeof AdminLimitesRoute
  AdminModulosRoute: typeof AdminModulosRoute
  AdminPlanosRoute: typeof AdminPlanosRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLimitesRoute: AdminLimitesRoute,
  AdminModulosRoute: AdminModulosRoute,
  AdminPlanosRoute: AdminPlanosRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesApiRoute: typeof AppConfiguracoesApiRoute
  AppConfiguracoesBrandingRoute: typeof AppConfiguracoesBrandingRoute
  AppConfiguracoesCadenciasRoute: typeof AppConfiguracoesCadenciasRoute
  AppConfiguracoesCamposRoute: typeof AppConfiguracoesCamposRoute
  AppConfiguracoesCentrosCustoRoute: typeof AppConfiguracoesCentrosCustoRoute
  AppConfiguracoesChecklistRoute: typeof AppConfiguracoesChecklistRoute
  AppConfiguracoesDominiosRoute: typeof AppConfiguracoesDominiosRoute
  AppConfiguracoesEquipeRoute: typeof AppConfiguracoesEquipeRoute
  AppConfiguracoesFunisRoute: typeof AppConfiguracoesFunisRoute
  AppConfiguracoesGoliveRoute: typeof AppConfiguracoesGoliveRoute
  AppConfiguracoesImobiliariaRoute: typeof AppConfiguracoesImobiliariaRoute
  AppConfiguracoesImportarRoute: typeof AppConfiguracoesImportarRoute
  AppConfiguracoesModulosRoute: typeof AppConfiguracoesModulosRoute
  AppConfiguracoesNotificacoesRoute: typeof AppConfiguracoesNotificacoesRoute
  AppConfiguracoesPlanoContasRoute: typeof AppConfiguracoesPlanoContasRoute
  AppConfiguracoesPrivacidadeRoute: typeof AppConfiguracoesPrivacidadeRoute
  AppConfiguracoesScoringRoute: typeof AppConfiguracoesScoringRoute
  AppConfiguracoesSegurancaRoute: typeof AppConfiguracoesSegurancaRoute
  AppConfiguracoesWebhooksRoute: typeof AppConfiguracoesWebhooksRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesApiRoute: AppConfiguracoesApiRoute,
  AppConfiguracoesBrandingRoute: AppConfiguracoesBrandingRoute,
  AppConfiguracoesCadenciasRoute: AppConfiguracoesCadenciasRoute,
  AppConfiguracoesCamposRoute: AppConfiguracoesCamposRoute,
  AppConfiguracoesCentrosCustoRoute: AppConfiguracoesCentrosCustoRoute,
  AppConfiguracoesChecklistRoute: AppConfiguracoesChecklistRoute,
  AppConfiguracoesDominiosRoute: AppConfiguracoesDominiosRoute,
  AppConfiguracoesEquipeRoute: AppConfiguracoesEquipeRoute,
  AppConfiguracoesFunisRoute: AppConfiguracoesFunisRoute,
  AppConfiguracoesGoliveRoute: AppConfiguracoesGoliveRoute,
  AppConfiguracoesImobiliariaRoute: AppConfiguracoesImobiliariaRoute,
  AppConfiguracoesImportarRoute: AppConfiguracoesImportarRoute,
  AppConfiguracoesModulosRoute: AppConfiguracoesModulosRoute,
  AppConfiguracoesNotificacoesRoute: AppConfiguracoesNotificacoesRoute,
  AppConfiguracoesPlanoContasRoute: AppConfiguracoesPlanoContasRoute,
  AppConfiguracoesPrivacidadeRoute: AppConfiguracoesPrivacidadeRoute,
  AppConfiguracoesScoringRoute: AppConfiguracoesScoringRoute,
  AppConfiguracoesSegurancaRoute: AppConfiguracoesSegurancaRoute,
  AppConfiguracoesWebhooksRoute: AppConfiguracoesWebhooksRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppSiteRouteChildren {
  AppSiteBlogRoute: typeof AppSiteBlogRoute
  AppSiteWidgetsRoute: typeof AppSiteWidgetsRoute
  AppSiteIndexRoute: typeof AppSiteIndexRoute
}

const AppSiteRouteChildren: AppSiteRouteChildren = {
  AppSiteBlogRoute: AppSiteBlogRoute,
  AppSiteWidgetsRoute: AppSiteWidgetsRoute,
  AppSiteIndexRoute: AppSiteIndexRoute,
}

const AppSiteRouteWithChildren =
  AppSiteRoute._addFileChildren(AppSiteRouteChildren)

interface AppContratosIdRouteChildren {
  AppContratosIdImprimirRoute: typeof AppContratosIdImprimirRoute
}

const AppContratosIdRouteChildren: AppContratosIdRouteChildren = {
  AppContratosIdImprimirRoute: AppContratosIdImprimirRoute,
}

const AppContratosIdRouteWithChildren = AppContratosIdRoute._addFileChildren(
  AppContratosIdRouteChildren,
)

interface AppRouteChildren {
  AppCartoriosRoute: typeof AppCartoriosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppContratacaoRoute: typeof AppContratacaoRoute
  AppEncurtadorRoute: typeof AppEncurtadorRoute
  AppPortaisRoute: typeof AppPortaisRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSiteRoute: typeof AppSiteRouteWithChildren
  AppTarefasRoute: typeof AppTarefasRoute
  AppVisitasRoute: typeof AppVisitasRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppContratosIdRoute: typeof AppContratosIdRouteWithChildren
  AppContratosModelosRoute: typeof AppContratosModelosRoute
  AppContratosNovoRoute: typeof AppContratosNovoRoute
  AppCorretoresIdRoute: typeof AppCorretoresIdRoute
  AppCorretoresNovoRoute: typeof AppCorretoresNovoRoute
  AppEmpreendimentosIdRoute: typeof AppEmpreendimentosIdRoute
  AppFinanceiroIdRoute: typeof AppFinanceiroIdRoute
  AppFinanceiroNovoRoute: typeof AppFinanceiroNovoRoute
  AppImoveisIdRoute: typeof AppImoveisIdRoute
  AppImoveisCompararRoute: typeof AppImoveisCompararRoute
  AppImoveisNovoRoute: typeof AppImoveisNovoRoute
  AppLeadsIdRoute: typeof AppLeadsIdRoute
  AppLeadsConfiguracaoRoute: typeof AppLeadsConfiguracaoRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppComissoesIndexRoute: typeof AppComissoesIndexRoute
  AppContratosIndexRoute: typeof AppContratosIndexRoute
  AppCorretoresIndexRoute: typeof AppCorretoresIndexRoute
  AppEmpreendimentosIndexRoute: typeof AppEmpreendimentosIndexRoute
  AppFinanceiroIndexRoute: typeof AppFinanceiroIndexRoute
  AppImoveisIndexRoute: typeof AppImoveisIndexRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
  AppLocacaoIndexRoute: typeof AppLocacaoIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCartoriosRoute: AppCartoriosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppContratacaoRoute: AppContratacaoRoute,
  AppEncurtadorRoute: AppEncurtadorRoute,
  AppPortaisRoute: AppPortaisRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSiteRoute: AppSiteRouteWithChildren,
  AppTarefasRoute: AppTarefasRoute,
  AppVisitasRoute: AppVisitasRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppContratosIdRoute: AppContratosIdRouteWithChildren,
  AppContratosModelosRoute: AppContratosModelosRoute,
  AppContratosNovoRoute: AppContratosNovoRoute,
  AppCorretoresIdRoute: AppCorretoresIdRoute,
  AppCorretoresNovoRoute: AppCorretoresNovoRoute,
  AppEmpreendimentosIdRoute: AppEmpreendimentosIdRoute,
  AppFinanceiroIdRoute: AppFinanceiroIdRoute,
  AppFinanceiroNovoRoute: AppFinanceiroNovoRoute,
  AppImoveisIdRoute: AppImoveisIdRoute,
  AppImoveisCompararRoute: AppImoveisCompararRoute,
  AppImoveisNovoRoute: AppImoveisNovoRoute,
  AppLeadsIdRoute: AppLeadsIdRoute,
  AppLeadsConfiguracaoRoute: AppLeadsConfiguracaoRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppComissoesIndexRoute: AppComissoesIndexRoute,
  AppContratosIndexRoute: AppContratosIndexRoute,
  AppCorretoresIndexRoute: AppCorretoresIndexRoute,
  AppEmpreendimentosIndexRoute: AppEmpreendimentosIndexRoute,
  AppFinanceiroIndexRoute: AppFinanceiroIndexRoute,
  AppImoveisIndexRoute: AppImoveisIndexRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
  AppLocacaoIndexRoute: AppLocacaoIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ContaRouteChildren {
  ContaBuscasRoute: typeof ContaBuscasRoute
  ContaFavoritosRoute: typeof ContaFavoritosRoute
  ContaPerfilRoute: typeof ContaPerfilRoute
  ContaVisitasRoute: typeof ContaVisitasRoute
  ContaIndexRoute: typeof ContaIndexRoute
  ContaChatIdRoute: typeof ContaChatIdRoute
  ContaChatIndexRoute: typeof ContaChatIndexRoute
}

const ContaRouteChildren: ContaRouteChildren = {
  ContaBuscasRoute: ContaBuscasRoute,
  ContaFavoritosRoute: ContaFavoritosRoute,
  ContaPerfilRoute: ContaPerfilRoute,
  ContaVisitasRoute: ContaVisitasRoute,
  ContaIndexRoute: ContaIndexRoute,
  ContaChatIdRoute: ContaChatIdRoute,
  ContaChatIndexRoute: ContaChatIndexRoute,
}

const ContaRouteWithChildren = ContaRoute._addFileChildren(ContaRouteChildren)

interface SiteSlugRouteChildren {
  SiteSlugPPageSlugRoute: typeof SiteSlugPPageSlugRoute
}

const SiteSlugRouteChildren: SiteSlugRouteChildren = {
  SiteSlugPPageSlugRoute: SiteSlugPPageSlugRoute,
}

const SiteSlugRouteWithChildren = SiteSlugRoute._addFileChildren(
  SiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  BuscarRoute: BuscarRoute,
  CalculadoraFinanciamentoRoute: CalculadoraFinanciamentoRoute,
  CalculadoraItbiRoute: CalculadoraItbiRoute,
  CalculadoraMudancaRoute: CalculadoraMudancaRoute,
  CalculadorasRoute: CalculadorasRoute,
  CompararRoute: CompararRoute,
  ContaRoute: ContaRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  LgpdRoute: LgpdRoute,
  LoginRoute: LoginRoute,
  MinhasBuscasRoute: MinhasBuscasRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  TermosRoute: TermosRoute,
  AvaliacaoTenantSlugRoute: AvaliacaoTenantSlugRoute,
  CorretorSlugRoute: CorretorSlugRoute,
  DocsApiRoute: DocsApiRoute,
  ImovelSlugRoute: ImovelSlugRoute,
  LSlugRoute: LSlugRoute,
  QueroAnunciarTenantSlugRoute: QueroAnunciarTenantSlugRoute,
  SiteSlugRoute: SiteSlugRouteWithChildren,
  VisitaCheckinTokenRoute: VisitaCheckinTokenRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicCronBuscasAlertasRoute: ApiPublicCronBuscasAlertasRoute,
  ApiPublicCronSnapshotRoute: ApiPublicCronSnapshotRoute,
  ApiPublicCronVisitasNotificacoesRoute: ApiPublicCronVisitasNotificacoesRoute,
  ApiPublicV1ImoveisRoute: ApiPublicV1ImoveisRoute,
  ApiPublicV1LeadsRoute: ApiPublicV1LeadsRoute,
  ApiPublicWebhooksDeliverRoute: ApiPublicWebhooksDeliverRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicFeedsTenantSlugOlxDotxmlRoute:
    ApiPublicFeedsTenantSlugOlxDotxmlRoute,
  ApiPublicFeedsTenantSlugVrsyncDotxmlRoute:
    ApiPublicFeedsTenantSlugVrsyncDotxmlRoute,
  ApiPublicSitemapTenantSlugSitemapDotxmlRoute:
    ApiPublicSitemapTenantSlugSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
